let empls = [{ "eid": 1, "ename": "Rani", "gender": "Female", "country": "Czech Republic" },
{ "eid": 2, "ename": "Georgia", "gender": "Female", "country": "Malaysia" },
{ "eid": 3, "ename": "Anya", "gender": "Female", "country": "Thailand" },
{ "eid": 4, "ename": "Marc", "gender": "Male", "country": "Sweden" },
{ "eid": 5, "ename": "Cherri", "gender": "Female", "country": "Sweden" },
{ "eid": 6, "ename": "Chiquita", "gender": "Female", "country": "Russia" },
{ "eid": 7, "ename": "Libby", "gender": "Female", "country": "Slovenia" },
{ "eid": 8, "ename": "Franzen", "gender": "Bigender", "country": "Tunisia" },
{ "eid": 9, "ename": "Padgett", "gender": "Male", "country": "Russia" },
{ "eid": 10, "ename": "Cos", "gender": "Male", "country": "Russia" },
{ "eid": 11, "ename": "Myrtie", "gender": "Genderqueer", "country": "Croatia" },
{ "eid": 12, "ename": "Beau", "gender": "Male", "country": "Brazil" },
{ "eid": 13, "ename": "Susann", "gender": "Female", "country": "Portugal" },
{ "eid": 14, "ename": "Bianka", "gender": "Female", "country": "Canada" },
{ "eid": 15, "ename": "Brucie", "gender": "Male", "country": "Bosnia and Herzegovina" },
{ "eid": 16, "ename": "Ax", "gender": "Male", "country": "Norway" },
{ "eid": 17, "ename": "Sheff", "gender": "Male", "country": "Russia" },
{ "eid": 18, "ename": "Crin", "gender": "Female", "country": "Mongolia" },
{ "eid": 19, "ename": "Hughie", "gender": "Male", "country": "Japan" },
{ "eid": 20, "ename": "Royal", "gender": "Male", "country": "Japan" },
{ "eid": 21, "ename": "Dermot", "gender": "Male", "country": "Sweden" },
{ "eid": 22, "ename": "Ludvig", "gender": "Male", "country": "Uganda" },
{ "eid": 23, "ename": "Noell", "gender": "Female", "country": "Chile" },
{ "eid": 24, "ename": "Brad", "gender": "Non-binary", "country": "Philippines" },
{ "eid": 25, "ename": "Cristian", "gender": "Male", "country": "Sweden" },
{ "eid": 26, "ename": "Elisabet", "gender": "Female", "country": "China" },
{ "eid": 27, "ename": "Koral", "gender": "Female", "country": "China" },
{ "eid": 28, "ename": "Drona", "gender": "Bigender", "country": "Japan" },
{ "eid": 29, "ename": "Lissa", "gender": "Female", "country": "Honduras" },
{ "eid": 30, "ename": "Jordana", "gender": "Female", "country": "China" },
{ "eid": 31, "ename": "Cloe", "gender": "Female", "country": "Philippines" },
{ "eid": 32, "ename": "Ardene", "gender": "Female", "country": "Russia" },
{ "eid": 33, "ename": "Koo", "gender": "Female", "country": "France" },
{ "eid": 34, "ename": "Carine", "gender": "Female", "country": "Indonesia" },
{ "eid": 35, "ename": "Libby", "gender": "Female", "country": "Japan" },
{ "eid": 36, "ename": "Susanna", "gender": "Female", "country": "Poland" },
{ "eid": 37, "ename": "Katine", "gender": "Female", "country": "Panama" },
{ "eid": 38, "ename": "Avigdor", "gender": "Male", "country": "France" },
{ "eid": 39, "ename": "Rhianon", "gender": "Female", "country": "Netherlands" },
{ "eid": 40, "ename": "Melania", "gender": "Female", "country": "Portugal" },
{ "eid": 41, "ename": "Van", "gender": "Male", "country": "Poland" },
{ "eid": 42, "ename": "Liv", "gender": "Female", "country": "Indonesia" },
{ "eid": 43, "ename": "Sean", "gender": "Female", "country": "Azerbaijan" },
{ "eid": 44, "ename": "Nelli", "gender": "Female", "country": "Kosovo" },
{ "eid": 45, "ename": "Tabor", "gender": "Male", "country": "Ukraine" },
{ "eid": 46, "ename": "Flin", "gender": "Male", "country": "Ethiopia" },
{ "eid": 47, "ename": "Charlean", "gender": "Female", "country": "Indonesia" },
{ "eid": 48, "ename": "Eben", "gender": "Male", "country": "Sweden" },
{ "eid": 49, "ename": "Emilee", "gender": "Female", "country": "China" },
{ "eid": 50, "ename": "Siffre", "gender": "Male", "country": "China" },
{ "eid": 51, "ename": "Lief", "gender": "Male", "country": "China" },
{ "eid": 52, "ename": "Prentice", "gender": "Male", "country": "China" },
{ "eid": 53, "ename": "Celia", "gender": "Female", "country": "Vietnam" },
{ "eid": 54, "ename": "Nona", "gender": "Female", "country": "Czech Republic" },
{ "eid": 55, "ename": "Toinette", "gender": "Female", "country": "Philippines" },
{ "eid": 56, "ename": "Siana", "gender": "Polygender", "country": "United States" },
{ "eid": 57, "ename": "Dorothee", "gender": "Female", "country": "Indonesia" },
{ "eid": 58, "ename": "Peder", "gender": "Male", "country": "Germany" },
{ "eid": 59, "ename": "Katti", "gender": "Female", "country": "China" },
{ "eid": 60, "ename": "Noble", "gender": "Male", "country": "Haiti" },
{ "eid": 61, "ename": "Henri", "gender": "Male", "country": "China" },
{ "eid": 62, "ename": "Rafaelia", "gender": "Female", "country": "China" },
{ "eid": 63, "ename": "Jocelyn", "gender": "Female", "country": "Russia" },
{ "eid": 64, "ename": "Audrye", "gender": "Non-binary", "country": "Ethiopia" },
{ "eid": 65, "ename": "Agnesse", "gender": "Female", "country": "China" },
{ "eid": 66, "ename": "Desiri", "gender": "Female", "country": "Indonesia" },
{ "eid": 67, "ename": "Kendrick", "gender": "Male", "country": "Kuwait" },
{ "eid": 68, "ename": "Charlotte", "gender": "Female", "country": "China" },
{ "eid": 69, "ename": "Sergio", "gender": "Male", "country": "Indonesia" },
{ "eid": 70, "ename": "Betti", "gender": "Female", "country": "Indonesia" },
{ "eid": 71, "ename": "Thurstan", "gender": "Male", "country": "Cambodia" },
{ "eid": 72, "ename": "Siusan", "gender": "Female", "country": "Indonesia" },
{ "eid": 73, "ename": "Loraine", "gender": "Female", "country": "France" },
{ "eid": 74, "ename": "Aurel", "gender": "Female", "country": "Canada" },
{ "eid": 75, "ename": "Prisca", "gender": "Female", "country": "Indonesia" },
{ "eid": 76, "ename": "Brody", "gender": "Male", "country": "Uruguay" },
{ "eid": 77, "ename": "Ruy", "gender": "Male", "country": "China" },
{ "eid": 78, "ename": "Jacinthe", "gender": "Female", "country": "China" },
{ "eid": 79, "ename": "Kin", "gender": "Male", "country": "Poland" },
{ "eid": 80, "ename": "Letitia", "gender": "Female", "country": "Indonesia" },
{ "eid": 81, "ename": "Arch", "gender": "Male", "country": "Sweden" },
{ "eid": 82, "ename": "Fidole", "gender": "Male", "country": "Indonesia" },
{ "eid": 83, "ename": "Drusilla", "gender": "Female", "country": "China" },
{ "eid": 84, "ename": "Rance", "gender": "Male", "country": "Indonesia" },
{ "eid": 85, "ename": "Sheri", "gender": "Female", "country": "Philippines" },
{ "eid": 86, "ename": "Naomi", "gender": "Bigender", "country": "China" },
{ "eid": 87, "ename": "Elisa", "gender": "Female", "country": "Philippines" },
{ "eid": 88, "ename": "Cass", "gender": "Female", "country": "Portugal" },
{ "eid": 89, "ename": "Rod", "gender": "Male", "country": "China" },
{ "eid": 90, "ename": "Cyndy", "gender": "Female", "country": "Canada" },
{ "eid": 91, "ename": "Kevina", "gender": "Female", "country": "Indonesia" },
{ "eid": 92, "ename": "Annabella", "gender": "Female", "country": "Poland" },
{ "eid": 93, "ename": "Clare", "gender": "Female", "country": "Poland" },
{ "eid": 94, "ename": "Fergus", "gender": "Male", "country": "France" },
{ "eid": 95, "ename": "Corry", "gender": "Female", "country": "Bangladesh" },
{ "eid": 96, "ename": "Hamish", "gender": "Male", "country": "Yemen" },
{ "eid": 97, "ename": "Kristina", "gender": "Female", "country": "Palestinian Territory" },
{ "eid": 98, "ename": "Jennine", "gender": "Female", "country": "Portugal" },
{ "eid": 99, "ename": "Kirsten", "gender": "Female", "country": "China" },
{ "eid": 100, "ename": "Gilbertine", "gender": "Polygender", "country": "Belarus" }]

console.log(empls.length);

let female_count = 0
for (let emp of empls) {
    if (emp.gender === 'Female' && emp.country === 'China') {
        female_count++;
    }
}

console.log("No of chinese female employees : ", female_count)


let male_count = 0
for (let emp of empls) {
    if (emp.gender === 'Male' && emp.country === 'Indonesia') {
        male_count++;
    }
}

console.log('No of Indonesian male employees : ', male_count)